aesirx_analytics.settings:
  type: config_object
  label: 'aesirx analytics settings'
  mapping:
    settings:
      type: mapping
      label: 'aesirx analytics default settings'
      mapping:
        1st_party_server:
          type: string
          label: '1st party server'
        consent:
          type: boolean
          label: 'consent'
        client_id:
          type: string
          label: 'client id'
        client_secret:
          type: string
          label: 'client secret'
        license:
          type: string
          label: 'license'
        domain:
          type: string
          label: 'domain'
    visibility:
      type: mapping
      label: 'Visibility'
      mapping:
        request_path_mode:
          type: integer
          label: 'Add tracking to specific pages'
        request_path_pages:
          type: string
          label: 'Pages by their paths'
        user_role_mode:
          type: integer
          label: 'Add tracking for specific roles'
        user_role_roles:
          type: sequence
          label: 'Roles'
          sequence:
            type: string
            label: 'Role'
        user_account_mode:
          type: integer
          label: 'Allow users to customize tracking on their account page'
